name: umd_documenter
description: Object Element Manager Library of Universal MarkDown Format. This package allows to handle Universal MarkDown Format in Dart app, like Flutter, AngularDart, Aqueduct, etc.
version: 0.1.3
repository: https://github.com/OpenDocument-Org/UMD_Format

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  matrix2d: ^1.0.0
