name: umd_tools
description: Parser & Trans-compiler of Universal MarkDown Format
version: 0.1.1
repository: https://github.com/OpenDocument-Org/UMD_Format

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  matrix2d: ^1.0.0
